# Generated by Django 5.1.4 on 2025-01-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_size', models.CharField(max_length=20)),
                ('item_category', models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Jacket', 'Jacket'), ('Other', 'Other')], default='Other', max_length=50)),
                ('item_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
