# Generated by Django 5.1.4 on 2025-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='cur_amount_on_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profit',
            name='gross_earning',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profit',
            name='gross_profit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profit',
            name='total_expenses_on_clothes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profit',
            name='total_expenses_on_other',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profit',
            name='total_expenses_on_shop',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profit',
            name='total_expenses_on_shopkeeper',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
