# Generated by Django 5.1.4 on 2025-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profit_cur_amount_on_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='cur_amount_on_bank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
