# Generated by Django 5.1.4 on 2025-01-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_selling_price_transactions_selling_price_offline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='gross_profit',
            field=models.IntegerField(default=0),
        ),
    ]
