# Generated by Django 5.1.4 on 2025-01-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profit_gross_profit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_size', models.CharField(max_length=20)),
                ('item_category', models.CharField(choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Jacket', 'Jacket'), ('Other', 'Other')], default='Other', max_length=50)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('item_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('item_date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
