# Generated by Django 5.1.4 on 2025-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_additem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='sale_profit',
            field=models.IntegerField(default=0),
        ),
    ]
